version: '3.9'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_zsh_dev
    volumes:
      - .:/code
      - zsh_history_python_01:/home/alx/zsh_history
      - vscode_extensions_python_01:/home/alx/.vscode-server/extensions
    ports:
      - 8000:8000
volumes:
  zsh_history_python_01:
    external: true
  vscode_extensions_python_01:
    external: true
